name: Run test deployment on any flow run failure
description: Automatically runs the test deployment whenever any flow run fails
enabled: true
trigger:
  type: event
  posture: Reactive
  expect:
    - prefect.flow-run.Failed
  threshold: 1
  for_each:
    - prefect.resource.id
actions:
  - type: run-deployment
    source: selected
    deployment_id: b091c6f6-906f-4f61-a4b2-a474a53a4b50
