[project]
name = "docs-mcp-server"
version = "0.1.0"
description = "MCP server for searching Prefect documentation using FastMCP and Turbopuffer"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.12.3",
    "logfire>=4.9.0",
    "openai>=1.109.1",
    "turbopuffer>=1.3.1",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]