name: CI

env:
  # Enable colored output
  PY_COLORS: 1

on:
  push:
    branches: ["main"]
    paths:
      - "evals/**/*.py"
      - "src/**"
      - "tests/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/**"

  pull_request:
    paths:
      - "evals/**/*.py"
      - "src/**"
      - "tests/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/**"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: "test: python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
      fail-fast: false
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}

      - uses: extractions/setup-just@v3

      - name: Run tests
        run: just test

  evals:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.12"

      - uses: extractions/setup-just@v3

      - name: Run evals
        id: run_evals
        continue-on-error: true
        run: |
          just evals --junit-xml=evals-results.xml --tb=short -v
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
          ENVIRONMENT: ci

      - name: Upload eval results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eval-results
          path: evals-results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            evals-results.xml
          check_name: Evaluation Results
          comment_mode: always
          fail_on: nothing

  lint:
    timeout-minutes: 2

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
        env:
          SKIP: no-commit-to-branch
